<?php
/**
 * Страница "Список языков".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Список языков</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/grid.png' ?>" />
    </div>
    <p>В списке отображаются все установленные языки.</p>
    <h2>Столбцы списка</h2>
    <ul class="g-help-list">
        <li><b>Язык / ID.</b> Уникальный идентификатор языка (код языка + код страны);</li>
        <li><b>Язык / Имя.</b> Имя языка;</li>
        <li><b>Язык / Полное имя.</b> Полное имя языка;</li>
        <li><b>Язык / Страна.</b> Принадлежность языка стране;</li>
        <li><b>Язык / Тег.</b> Тег языка;</li>
        <li><b>Язык / Локаль.</b> Локаль языка;</li>
        <li><b>Язык / По умолчанию.</b> Установлен язык, как язык по умолчанию;</li>
        <li><b>Доступен / Сайт.</b> Доступность выбора языка для сайта;</li>
        <li><b>Доступен / Панель.</b> Доступность выбора языка для Панели управления;</li>
        <li><b>Статус.</b> Статус языка (установлен, не установлен).</li>
    </ul>

    <h2>Панель инструментов</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-install.svg' ?>" /> <b>Установить.</b> Устанавливает выбранный язык;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-uninstall.svg' ?>" /> <b>Удалить.</b> Удаляет выбранный язык;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-edit.svg' ?>" /> <b>Правка.</b> Вызвает форму для просмотра информации о языке;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Обновить.</b> Обновляет список языков;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Профилирование записи.</b> Разворачивает или сворачивает Панель навигации для отображения информации о выбранном языке;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-toggle-columns-off.svg' ?>" /> <b>Показать / Скрыть.</b> Показывает или скрывает столбцы;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Справка.</b> Вызывает окно справочной информации для текущего списка;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Поиск.</b> Вызывает форму поиска записей в списке;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/filter.svg' ?>" /> <b>Фильтр.</b> Вызывает форму фильтрации записей в списке.</li>
    </ul>
</article>