<?php
/**
 * Страница "Список языков".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>List of languages</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/grid.png' ?>" />
    </div>
    <p>The list displays all installed languages.</p>
    <h2>List columns</h2>
    <ul class="g-help-list">
        <li><b>Language / ID.</b> Unique language identifier (language code + country code);</li>
        <li><b>Language / Name.</b> Language name;</li>
        <li><b>Language / Full name.</b> Language full name;</li>
        <li><b>Language / Country.</b> Belonging of language to country;</li>
        <li><b>Language / Tag.</b> Language tag;</li>
        <li><b>Language / Locale.</b> Language locale;</li>
        <li><b>Language / By default.</b> Set language as default language;</li>
        <li><b>Available / Site.</b> Availability of language selection for the site;</li>
        <li><b>Available / Panel Control.</b> Availability of language selection for Control Panel.</li>
        <li><b>Status.</b> Language status (installed, not installed).</li>
    </ul>

    <h2>Toolbar</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-install.svg' ?>" /> <b>Install.</b> Sets the selected language;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-uninstall.svg' ?>" /> <b>Delete.</b> Delete the selected language;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-edit.svg' ?>" /> <b>Edit.</b> Shows the form to view language information;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Refresh.</b> Refresh the list of languages;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Record profiling.</b> Expands or collapses the Navigation Bar to display information about the selected language;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-toggle-columns-off.svg' ?>" /> <b>Show / Hide.</b> Shows or hides columns;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Help.</b> Show the help window for the current list;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Search.</b> Shows the form for searching records in the list;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/filter.svg' ?>" /> <b>Filter.</b> Shows the form for filtering records in a list.</li>
    </ul>
</article>